### PR TITLE
Support for using prebuilt binaries

### PR DESCRIPTION
**Pull request by unya**
New `configure` option, `--prebuilt` which causes the build process to use official builds from NodeJS site.

Debug builds now use prebuilt by default

### CODE REVIEW

**Review by Elexy — COMMENTED** [review]
LGTM

**Comment by conoro** [comment]
@unya @Elexy Whilst we can just grab the binary, we want to highlight the build-from-source aspect of the supported offering. We want to be able to say "we've built this from source, we've run all the unit tests (I know we don't yet) and we can confirm that this is a good release". 

Are there any optimisations possible when compiling for specific OSes? e.g. could a binary built for RHEL have particular compiler flags that make it more high performance on their kernel?

**Comment by Elexy** [comment]
@conoro I'd use this primarily to test the pipeline.

**Comment by conoro** [comment]
👍

**Pull request merged**
